### ISSUE TITLE
Setting non-crossover gene conversion

### ISSUE THREAD

**Issue by kiwizhu99** [pierpal/ARGON#1]
I was confused about how to set up the parameters for gene conversion rate. Suppose I'm using the constant genetic map (1cM=1Mb) and setting -rec 1E-8. Does -GC 1 set the non-crossover gene conversion rate to be 1E-8 or 5E-9?  Thanks for your explanation!

**Comment by pierpal** [comment]
Hi kiwizhu99, the recombination rate is independent of whether "-GC" is active or not, and determines the overall probability of a recombination event. Recombination can be crossover or non-crossover (inactive by default, activated with "-GC"). The parameter of the "-GC" flag indicates the relative rate of non-crossover events. Given a recombination event has been sampled (with rate given in "-rec"), it will be a crossover with probability 1/(1+GC), and non-crossover with probability GC/(1+GC). For instance, If you set "-GC 1", non-crossover events will be as likely as crossover events.
Example: "-rec 1E-8 -GC 1.0" --> recombination events are sampled with rate 1E-8, and when a recombination happens, it is crossover with probability 1/(1+1)=1/2, or non-crossover with probability 1/(1+1)=1/2. This means both crossover and non-crossover have rate 5E-9. 
If "-rec 1E-8 -GC 6.0" --> when a recombination happens, it is crossover with probability 1/(1+6)=1/7, or non-crossover with probability 6/(1+6)=6/7.
Hope this helps.
